server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mmmjj/msa-config
        native:
          search-locations: file:///D:/mmmj/workspace/gitworkspace/msa_config_native
#          uri: file://D:/locate/msa_config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
