server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes: #???? route?? ???? ????
        - id: first-service
          uri: http://127.0.0.1:8081/ # path? ??? ?.. http://127.0.0.1:8000/first-service/welcome -> http://127.0.0.1:8081/first-service/welcome
          predicates: #????? ???
            - Path=/first-service/**
        - id: second-service
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/second-service/**


